### ISSUE TITLE
jpm post does not work in 1.2.1 because of TypeError: logger.info is not a function

### ISSUE THREAD

**Issue by frigus02** [mozilla-jetpack/jpm#596]
I just updated to jpm version 1.2.1 and found, that the post command no longer works. It throws the following error:

```
> jpm post --post-url http://127.0.0.1:8888
JPM [info] Starting jpm post on RESTer

C:\Users\Jan\AppData\Roaming\npm\node_modules\jpm\lib\post.js:48
            logger.info("Posted XPI to " + postURL);
                   ^
TypeError: logger.info is not a function
    at Socket.<anonymous> (C:\Users\Jan\AppData\Roaming\npm\node_modules\jpm\lib\post.js:48:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

I updated from version 1.1.4, so it's possible the error was already introduced in 1.2.0.

**Comment by freaktechnik** [comment]
It seems the console exported by utils only has these functions: https://github.com/mozilla-jetpack/jpm/blob/master/lib/utils.js#L36-L41

**Comment by frigus02** [comment]
Right, and post.js already uses them: https://github.com/mozilla-jetpack/jpm/blob/master/lib/post.js#L13

However I think the function is called `log`, not `info`.

**Comment by freaktechnik** [comment]
Exactly. This was an oversight in #587

**Comment by kumar303** [comment]
Oops. Unfortunately, no one ever wrote tests for `jpm post` so it breaks a lot. Sorry.

**Comment by kumar303** [comment]
I fixed it in this patch ^ and opened an issue about adding test coverage: https://github.com/mozilla-jetpack/jpm/issues/598

**Comment by kumar303** [comment]
This was released in jpm 1.2.2, sorry about the hassle. https://www.npmjs.com/package/jpm

**Comment by frigus02** [comment]
Nice, it works. Thanks for the quick resolution.
