### ISSUE TITLE
jpm breaks with node 7+

### ISSUE THREAD

**Issue by schalkneethling** [mozilla-jetpack/jpm#604]
When running jpm with Node 7+, jpm breaks with the following error:

```
$ jpm --version
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/usr/local/lib/node_modules/jpm/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

When running against 6.9.4, jpm works but, the following warning is output in the terminal:

`(node:36785) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`

**Comment by kumar303** [comment]
What version of npm did you install it with? 

If you need a quick fix, Node 6 is known to work. You could use [nvm](https://github.com/creationix/nvm) to put both versions on your system easily.

**Comment by kumar303** [comment]
In both cases it seems like it could be an npm bug (of which there are many). Try doing this in each Node version:

    npm uninstall -g jpm

Upgrade npm, then run:

    npm install -g jpm

**Comment by schalkneethling** [comment]
It works with version 6.9.4 but, anything 7+ throws the error from above. I did do the uninstall and reinstall as well but, with version 7+ it does not work.

**Comment by yan12125** [comment]
Most likely wrong installations.
```
$ node --version && npm --version && jpm --version
v7.4.0
4.0.5
1.2.2
```

@schalkneethling It would be helpful if you post the log of ```npm install -g jpm```

**Comment by schalkneethling** [comment]
@yan12125 At this point it is working so, I am going to close this and will reopen with more info should I run into the problem again.

To be honest, it might have something to do with updating node via `npm g`

I have now switched to `nvm` and so far, so good. Thanks!

**Comment by kumar303** [comment]
@schalkneethling thanks for the bug report! Sorry about the hassle.
